font_family Fira Code
font_size 14
enable_ligatures yes

background            #1F1F28
background_opacity    0.88
cursor                #c3e88d
cursor_text_color     #1e2030

hide_window_decorations yes
enable_audio_bell no
visual_bell_duration 0

shell zsh
